### ISSUE TITLE
Regarding .h5 file

### ISSUE THREAD

**Issue by niharikanaidu** [Uday47/Smart-Attendance-System-using-Computer-Vision-#1]
Hello uday, Your project was interesting! Where can I get .h5 file i e you have used for weights?and where can I connect with you to discuss about this project.?

**Comment by Uday47** [comment]
Hi. 
Thanks for reaching out.
I have now added the file to the repo.
You can reach out to me on LinkedIn at https://www.linkedin.com/in/uday-sai-savitha/

**Comment by niharikanaidu** [comment]
Thank you!
